import { allCategoriesUnified as categories, allBrandsUnified, isBrandNoindex, getAllBrandSlugs } from '@/data/allBrandsIndex';
import { seriesIndex } from '@/data/series/_index';
import { blogArticles } from '@/data/blog';
import { caseStudies } from '@/data/caseStudies';
import { lastModified } from '@/data/lastModified';
import { config } from '@/lib/config';

const BASE_URL = config.site.url;

export default function sitemap() {
  // Real lastModified dates sourced from git history of the content/data files
  // that drive each group - see src/data/lastModified.js. Bump the relevant
  // date there whenever you edit a page or a data file, so Google sees an
  // accurate freshness signal instead of a stale hardcoded date.

  // Static pages
  const staticPages = [
    {
      url: BASE_URL,
      lastModified: lastModified.home,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/contact`,
      lastModified: lastModified.contact,
      changeFrequency: 'yearly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/despre-noi`,
      lastModified: lastModified.despreNoi,
      changeFrequency: 'yearly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog`,
      lastModified: lastModified.blog,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/studii-de-caz`,
      lastModified: lastModified.studiiDeCaz,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/industrii`,
      lastModified: lastModified.industrii,
      changeFrequency: 'yearly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/faq`,
      lastModified: lastModified.faq,
      changeFrequency: 'yearly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/certificari`,
      lastModified: lastModified.certificari,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${BASE_URL}/testimoniale`,
      lastModified: lastModified.testimoniale,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/ghid-comparativ`,
      lastModified: lastModified.ghidComparativ,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/ghid-achizitii-seap`,
      lastModified: lastModified.ghidAchizitiiSeap,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/gdpr`,
      lastModified: lastModified.gdpr,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/politica-confidentialitate`,
      lastModified: lastModified.politicaConfidentialitate,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/politica-cookies`,
      lastModified: lastModified.politicaCookies,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/termeni-si-conditii`,
      lastModified: lastModified.termeniSiConditii,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/echipa`,
      lastModified: lastModified.echipa,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/echipamente-diverse`,
      lastModified: lastModified.echipamenteDiverse,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  ];

  // Brand A–Z index (src/app/brand/page.js) — the crawl path to every brand page
  const brandIndexPage = {
    url: `${BASE_URL}/brand`,
    lastModified: lastModified.brands,
    changeFrequency: 'weekly',
    priority: 0.8,
  };

  // /branduri-sua hub (v12) — every US manufacturer, by category and industry
  const usBrandsPage = {
    url: `${BASE_URL}/branduri-sua`,
    lastModified: lastModified.brands,
    changeFrequency: 'weekly',
    priority: 0.8,
  };

  // Category pages
  const categoryPages = categories.map((category) => ({
    url: `${BASE_URL}/${category.slug}`,
    lastModified: lastModified.categories,
    changeFrequency: 'weekly',
    priority: 0.9,
    ...(category.image && { images: [`${BASE_URL}${category.image}`] }),
  }));

  // Brand pages (unified, simple slugs) — excludes noindex brands (isBrandNoindex)
  // (src/data/noindexBrands.js, generated by scripts/build-noindex.mjs):
  // those pages stay live and crawlable (robots: index:false, follow:true)
  // but do not belong in the sitemap we ask Google to crawl from.
  const brandPages = allBrandsUnified
    .filter((brand) => !isBrandNoindex(brand.simpleSlug))
    .map((brand) => ({
    url: `${BASE_URL}/brand/${brand.simpleSlug}`,
    lastModified: lastModified.brands,
    changeFrequency: 'weekly',
    priority: 0.8,
    ...(brand.logo && brand.logo !== '/brands/placeholder.png' && { images: [`${BASE_URL}${brand.logo}`] }),
  }));

  // Series pages (/brand/<brand>/<serie>) — decisions-architecture.md B:
  // priority 0.7, monthly, lastModified = the series' own dateModified.
  const liveBrandSlugs = new Set(getAllBrandSlugs());
  const seriesPages = seriesIndex
    .filter((s) => liveBrandSlugs.has(s.brand))
    .map((s) => ({
      url: `${BASE_URL}/brand/${s.brand}/${s.slug}`,
      lastModified: s.dateModified,
      changeFrequency: 'monthly',
      priority: 0.7,
    }));

  // Industry pages (to be added later)
  const industryPages = [
    'petrochimie',
    'alimentar',
    'tratare-apa',
    'energie',
    'farmaceutic',
    'chimie',
    'minerit',
    'constructii',
    'automotive',
    'metalurgie',
    'ciment',
    'hartie',
    'logistica',
    'biogaz',
    'naval',
  ].map((industry) => ({
    url: `${BASE_URL}/industrii/${industry}`,
    lastModified: lastModified.industries,
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Blog article pages - use actual article dates when available
  const blogPages = blogArticles.map((article) => ({
    url: `${BASE_URL}/blog/${article.slug}`,
    lastModified: article.dateModified || article.date || lastModified.blog,
    changeFrequency: 'monthly',
    priority: 0.7,
    ...(article.image && { images: [`${BASE_URL}${article.image}`] }),
  }));

  // Case study pages
  const caseStudyPages = caseStudies.map((cs) => ({
    url: `${BASE_URL}/studii-de-caz/${cs.slug}`,
    lastModified: lastModified.caseStudies,
    changeFrequency: 'monthly',
    priority: 0.8,
  }));

  return [
    ...staticPages,
    ...categoryPages,
    brandIndexPage,
    usBrandsPage,
    ...brandPages,
    ...seriesPages,
    ...industryPages,
    ...blogPages,
    ...caseStudyPages,
  ];
}
